server:
  port: 8090

spring:
  application:
    name: HabitTracker
  security:
    user:
      name: admin
      password: admin
  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@habittracker.zdiec.mongodb.net
      database: ${DB_NAME}